# -*- coding: utf-8 -*-
"""inference_SRGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_QZGXLUHjvu91uiY67_9XFQwAVV2a7K

# Inference for SRGAN
"""

import os
import subprocess

from PIL import Image

# Path results
# DDPM 512 3.7k sector
path_data = "../../Data/dazzly/for_segmentation/one_color_per_symbol/4096/4096_bw_test/LR"
path_model = '../../Results/dazzly/SR/SRGAN_x4-SRGAN_dazzly_4k/SRGAN_x4_g_16_ep.pth.tar'
path_results = '../../Results/dazzly/SR/SRGAN_x4-SRGAN_dazzly_4k/inference'

if os.path.exists(path_results) == False:
    os.makedirs(path_results)
    print(f"Created {path_results}")

"""## Inference"""

# Image input
name_image = 'mandala_2524_bw.png'
input = os.path.join(path_data, name_image)


# Read the image
image = Image.open(input)

# Apply spatial smoothing with cubic interpolation
smoothed_image = image.resize(image.size, Image.BICUBIC)

# Save the smoothed image temporarily
smoothed_image_path = os.path.join(path_data, name_image.replace(".png", "_sm.png"))
smoothed_image.save(smoothed_image_path)

# Ouput
name_output = name_image.replace(".png", "_srganx4.png")
output = os.path.join(path_results, name_output)
print(f"Output: {output}")

subprocess.run(["python3", "./inference.py", "--inputs", input, 
                "--model_weights_path", path_model, 
                "--output", output ])

